name: lachanarchy-main
version: '${project.version}'
main: eu.felicianware.lachanarchymain.Main
api-version: '1.20'
folia-supported: true
commands:
  discord:
    description: Provides the Discord link.
    usage: /discord
  help:
    description: Get help.
    usage: /help
  kill:
    description: Kills you.
    usage: /kill