name: lachanarchy-main
version: '${project.version}'
main: eu.felicianware.lachanarchymain.Lachanarchy_main
api-version: '1.20'
commands:
  discord:
    description: Provides the Discord link.
    usage: /discord