name: lachanarchy-main
version: '1.0-SNAPSHOT'
main: eu.felicianware.lachanarchymain.Lachanarchy_main
api-version: '1.20'
folia-supported: true
commands:
  discord:
    description: Provides the Discord link.
    usage: /discord
  help:
    description: Get help.
    usage: /help
  kill:
    description: Kills you.
    usage: /kill